### ISSUE TITLE
More of a question...

### ISSUE THREAD

**Issue by Lucero7919** [jakewalsh90/Terraform-Azure#2]
In azuredeploy.tf in the resource windows virtual machine you have:
  protected_settings = <<PROTECTED_SETTINGS
    {
      "commandToExecute": "powershell.exe -Command \"./baselab_DCSetup.ps1; exit 0;\""
    }
  PROTECTED_SETTINGS

  settings = <<SETTINGS
    {
        "fileUris": [
          "https://raw.githubusercontent.com/jakewalsh90/Terraform-Azure/main/Single-Region-Azure-BaseLab/PowerShell/baselab_DCSetup.ps1"
        ]
    }
  SETTINGS

Why? The files are listed in the "powershell" folder. Are they not copied to the VM during deployment? Or are they just there for reference?

If the file is downloaded from github, what tells the vm where to copy the file to?

**Comment by jakewalsh90** [comment]
The initial file (baselab_DCSetup.ps1) is downloaded and run by the Custom Script extension within azuredeploy.tf. However the other two files (Domain Setup and Lab Setup) are downloaded to the VM by using the Invoke-WebRequest command in the baselab_DCSetup.ps1 file (run by the custom script extension). This places the other two PowerShell files (amongst other things) onto the VM ready for setup later if a functional DC is required.

**Comment by jakewalsh90** [comment]
Some extra info on the final steps required to complete the setup here: https://github.com/jakewalsh90/Terraform-Azure/blob/main/Single-Region-Azure-BaseLab/README.md#manual-steps-to-complete-lab-environment

**Comment by Lucero7919** [comment]
Jake, thanks for the reply. Do you know, or have you tried doing the invoke web request from an Azure storage account using private links?

**Comment by Lucero7919** [comment]
> Some extra info on the final steps required to complete the setup here: https://github.com/jakewalsh90/Terraform-Azure/blob/main/Single-Region-Azure-BaseLab/README.md#manual-steps-to-complete-lab-environment

Any update Jake? Also, I notice that you say you download the file using the custom script extension, but you also just call it in the settings block. Surely that means you don't need to download it if that file lives in the PowerShell folder

**Comment by jakewalsh90** [comment]
Hiya - the first script runs the setup, but within that script others are downloaded to the VM and saved, so that some setup elements can be manually triggered and finished later. I'd prefer to keep them in my GitHub account for now rather than storage as I can manage them all in one place then :)
