### ISSUE TITLE
Single Region Base Lab Environment for Azure

### ISSUE THREAD

**Issue by florian-ried** [jakewalsh90/Terraform-Azure#3]
I am very grateful to you for your code 
I'm just trying to deploy the single region base lab environment via terraform and git hub actions
I'm still there after 30 minutes: 

![image](https://user-images.githubusercontent.com/95634472/148561366-9846eae6-6401-48bb-99e4-979352365949.png)
Should the code still work? 
Thank you so much!

Best Regards
Florian

**Comment by florian-ried** [comment]
example with dual region is completly deployed..
only in the single region base lab the timeout occurs

**Comment by jakewalsh90** [comment]
Hi! I have just tested the single region lab without any issues in my own environment - please can you test the single one again and see if the issue comes back? If so - please share any logs so I can look into this 👍

**Comment by florian-ried** [comment]
Today it worked with exactly the same code :) Which steps are still necessary to provide a domain controller? Running PowerShell under C: \ BaseLabSetup ends with the following error: 
![image](https://user-images.githubusercontent.com/95634472/148694792-4feac1ad-d2d8-4878-88ec-9b39c5ce2a0e.png)

**Comment by jakewalsh90** [comment]
That error suggests that you don't have a data disk attached to the VM - the script extension run during the Azure Deployment should set this up and initialise the disk. Then you just need to run baselab_DomainSetup.ps1, then the VM will reboot, and then finally baselab_LabSetup.ps1.

**Comment by florian-ried** [comment]
Thank you!. My drive has been assigned the letter F. Of course after I changed that in the script everything worked. ;-) 

![image](https://user-images.githubusercontent.com/95634472/148734117-32559467-0075-4ba9-9942-7aad00d1a784.png)

**Comment by florian-ried** [comment]
d
