### ISSUE TITLE
Missing required argument - sku_name (Azure Firewall)

### ISSUE THREAD

**Issue by realnamesareboring** [jakewalsh90/Terraform-Azure#5]
So when deploying the Azure-Firewall-DemoLab Im getting an error stating its missing an argument. Just messing around and familiarizing myself with terraform so wondering if you could point me in the right direction with this one.

Out of all the terraform firewall examples this one seems the most thorough so any help you could provide would be most appriciated. Thank you!

Below is the snippet.

 Error: Missing required argument
│
│   on azuredeploy.tf line 334, in resource "azurerm_firewall" "region1-fw01":
│  334: resource "azurerm_firewall" "region1-fw01" {
│
│ The argument "sku_name" is required, but no definition was found.

**Comment by jakewalsh90** [comment]
Thank you for raising this - now fixed and tested working 👍
