### ISSUE TITLE
Terraform Destroy (No changes. No objects need to be destroyed.)

### ISSUE THREAD

**Issue by dimi4ik** [jakewalsh90/Terraform-Azure#8]
Hello Jake,
Thank you for the Interstate Meeting last week. 🥇 

I have now copied your Git repo and executed the Git action "Terraform Validate, Plan, and Apply" for the Single-Region-Azure-BaseLab-v2. 
The Azure resources were successfully provisioned. 
Cool, thanks!  👍 

Now, when I try to delete the resources using the "Terraform Destroy" action, 
I receive the following message: "No changes. No objects need to be destroyed." 

Do you have any ideas or tips on what to do?

**Comment by jakewalsh90** [comment]
Hi, hope you're well! It is most likely that the directory has not been set on the destroy action in your repo (where it says working-directory: ./your-tf-directory). Without this set the destroy action will not be referencing the same repository as the apply action.
